"""AI 테이블 추가

Revision ID: 12c65146e166
Revises: 230242d3ddb9
Create Date: 2025-09-08 16:06:29.609076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12c65146e166'
down_revision = '230242d3ddb9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 