"""AI 테이블 추가 (수정)

Revision ID: d8d77a99be41
Revises: 12c65146e166
Create Date: 2025-09-08 16:07:27.257317

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = 'd8d77a99be41'
down_revision = '12c65146e166'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('column_descriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('column_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_column_descriptions_column_name'), 'column_descriptions', ['column_name'], unique=False)
    op.create_index(op.f('ix_column_descriptions_id'), 'column_descriptions', ['id'], unique=False)
    op.create_index(op.f('ix_column_descriptions_table_name'), 'column_descriptions', ['table_name'], unique=False)
    op.create_table('column_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('column_id', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['column_id'], ['column_descriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_column_embeddings_id'), 'column_embeddings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_column_embeddings_id'), table_name='column_embeddings')
    op.drop_table('column_embeddings')
    op.drop_index(op.f('ix_column_descriptions_table_name'), table_name='column_descriptions')
    op.drop_index(op.f('ix_column_descriptions_id'), table_name='column_descriptions')
    op.drop_index(op.f('ix_column_descriptions_column_name'), table_name='column_descriptions')
    op.drop_table('column_descriptions')
    # ### end Alembic commands ### 